### ISSUE TITLE
使用初体验反馈

### ISSUE THREAD

**Issue by BopSun** [verlorengest/BlenderManager#1]
Hi~

我用中文输入可以快速进行反馈，同样的，你们也可以使用英语回复我，我可以通过翻译软件获悉你们的答复。

我很高兴你们开发了这个工具，看起来它扩展了 Blender Launcher 的功能，所以我计划用它来替代。我在Gumroad上支持了你们并希望得到这个工具的更新提示。

我知道你们有自己的发展路线，所以我仅根据目前的使用经验提出一些感觉不太方便的地方，希望能够得到一些改善：

- 我觉得 Installed Versions 有些多余，可以把它整合到 Main Menu 做成下拉菜单选择启动。
![image](https://github.com/user-attachments/assets/dd908363-fd81-491c-b78d-50f57533d158)
- Installation 中的版本列表能不能把最新版本放置在顶部？最好能参考 Blender Launcher 的做法，按发布时间顺序，或是能做一个排序列表让用户自己选择排列顺序。
- 对于项目来说有一个重要的信息是不同的项目会使用不同版本的 Blender，如果你们能记录项目使用的 Blender 版本，那就太好了。
- 对于同一个项目，我会使用增量保存多个版本，而这会给你们的项目列表带来混乱，所以，这里需要一个方法能够区分这些，包括按文件夹进行分类。
![image](https://github.com/user-attachments/assets/c0d6b765-241a-4023-b23d-7cf1fbf14d23)
- 插件管理部分我很喜欢，但是我发现它不能正确识别一些插件的版本信息。
![image](https://github.com/user-attachments/assets/d667af51-58e5-445b-ad3b-867b2fd63982)
- 我目前的方法是使用文件夹层级管理不同的项目，一个大的项目中包括不同的小任务，每个任务中还包括不同阶段的文件管理，比如Blender，ZBrush，Baker，Submit等。在最终的Blender文件夹内才是Blender文件（包含增量版本和自动保存）。我暂时还没想好如何将这个工具与我的项目管理进行配合。或许你们能给出一些建议？

你们有个不错的开始，我希望这个工具能够发展成为一个人人需要的必备工具。

谢谢！

Bop

**Comment by verlorengest** [comment]
Thank you so much for your feedback and support! I appreciate your detailed suggestions. I have taken your points into consideration:

Your idea to place the most recent version at the top of the installation list makes perfect sense, and I will implement this in the next update.

Detecting and saving the specific Blender version used for each project is indeed challenging, but I understand its importance and will work on finding a suitable solution.

Regarding the issue with plugin version recognition, could you please navigate to the plugin's folder and send me a screenshot of its file hierarchy? This will help me better understand the problem and work towards a fix.

You will soon be able to fully manage your Blender projects within the Project Management section. However, I still need to implement a few fixes in that area, so stay tuned for the next update.

I aim to resolve as many issues as possible before the official release of the program. Your testing and reporting of any bugs or issues you encounter are invaluable. Thank you again for your interest and support.

Best regards,
Kaan

**Comment by BopSun** [comment]
Hi Kaan，

关于项目使用 Blender 版本我的方法是在建立 Blender 文件夹时，在文件夹命名中进行标注，比如「Blender 4.2」或「Blender 3.6」。但如果是通过 BlenderManager 启动项目的话，我猜想在创建或启动项目时的选择应该能够被存储下来作为一个标识。

插件识别问题目前我只发现了这个，更多关于识别问题可能需要更多的用户反馈才能获取到。毕竟每个插件开发者的习惯可能都不尽相同。
![image](https://github.com/user-attachments/assets/e0814df4-b7d0-4fd0-85d4-0b4bc1fb54d2)
关于截图上第二个应该是某个插件生成的文件夹，我觉得你可以将其从列表中排除。
![image](https://github.com/user-attachments/assets/42275e7f-a6e8-4b9e-9137-5577cfca7718)

我使用 [PowerSave](https://bonjorno7.gumroad.com/l/powersave) 插件来防止数据意外丢失。我不清楚创建项目时的自动保存机制是如何运作的，它与 Blender 内部的自动保存或该插件的保存机制是否有冲突？如果你提供了这些选项，那么它的清理机制是什么？
![image](https://github.com/user-attachments/assets/ed0fa61c-c2cb-4729-8a47-a4c7ab5cb4b1)

谢谢！

Bop

**Comment by verlorengest** [comment]
Hello Again,

Thanks for sharing the screenshots! I will fix the issue asap.  

When you enable the Auto-Save option while creating a project, your project will be automatically saved at the specified interval you choose. If you also check the Save as Different Files Each Time option, the program will not overwrite the existing file but will instead create a new file with each save. The filenames are generated randomly, but you can rename them later if needed.

I am currently working on a feature that will allow users to pre-configure how the project should be saved, and you can expect this in the next release.

The Auto-Save function in Blender Manager is designed to work seamlessly and should not conflict with any other auto-save plugins you might be using. It also does not interfere with Blender’s built-in save functionality. If you choose to manually save your project using Blender’s "Save As" option, you can do so without any issues. However, please note that if you use the "Save" button, it will overwrite the last auto-saved file.

Best Regards,
Kaan

**Comment by BopSun** [comment]
Hi  Kaan

我明白了，感谢你的回复，期待新版本的发布。

谢谢~

bop
