### ISSUE TITLE
Download failed (Virus detected)

### ISSUE THREAD

**Issue by Xylvier** [verlorengest/BlenderManager#2]
![image](https://github.com/user-attachments/assets/9a8c7f74-5a40-46da-be24-a3dd27378060)

Not sure what triggered the virus alarm, but I'd recommend to check and/or mention any reason why (if there is a false-positive) that may happen.

Hope you can solve that before all those wanting to try like me get the wrong impression.
Best regards.

**Comment by verlorengest** [comment]
Hi there,

This is a false positive, often seen with new .exe files. The app is safe, but since it’s not widely recognized yet, antivirus programs may flag it incorrectly. If you encounter issues, you can also run it directly from the source code.

Best regards!
