### ISSUE TITLE
When I unzip the Blender Manager archive, there is no blender_manager.exe  file

### ISSUE THREAD

**Issue by mpwillner** [verlorengest/BlenderManager#3]
According to the installation instructions, there should be a blender_manager.exe  file after unpacking the zip file. It is missing in the download: BlenderManager-main.zip.

**Comment by verlorengest** [comment]
Hi there,

It looks like you might have downloaded the source code instead. Please ensure you’re using the release file from this link:

[BlenderManager v0.0.2 Release](https://github.com/verlorengest/BlenderManager/releases/download/v0.0.2/blender_manager_v0.0.2.zip)

The .exe file is included in the release version, not in the source code download.

Best regards!

**Comment by mpwillner** [comment]
I eventually found that. When I clicked on the original link it took me to
the main and I downloaded from there.

Thank you for responding so quickly. I found all the files.

*Mark Willner*
