### ISSUE TITLE
Chinese Simplified 

### ISSUE THREAD

**Issue by lonely814** [verlorengest/BlenderManager#4]
[simplified Chinese.csv] (https://github.com/user-attachments/files/17824759/simplified.Chinese.csv)

Hi Author 
This is a term for Chinese Simplified

I don't know if it will help you, but I've translated as many terms as I can find and I'm not sure if the format I've given you can directly help you

**Comment by lonely814** [comment]
[simplified Chinese.csv](https://github.com/user-attachments/files/17824896/simplified.Chinese.csv)

Something seemed to be missing. I filled it in.

**Comment by verlorengest** [comment]
Thank you for your translation efforts. The terms you've provided will be reviewed and integrated into the project in an upcoming update following a few patches. Your contribution is greatly appreciated.
