### ISSUE TITLE
Addons menegment

### ISSUE THREAD

**Issue by AlexRom63-byte** [verlorengest/BlenderManager#5]
It would be really nice to add the ability to enable/disable addons

**Comment by verlorengest** [comment]
**Hey!**  

I’m already testing that feature. Feel free to try it out in the latest release!  
[[BlenderManager v0.0.8](https://github.com/verlorengest/BlenderManager/releases/tag/v0.0.8)](https://github.com/verlorengest/BlenderManager/releases/tag/v0.0.8)

**Comment by verlorengest** [comment]
**Hey!**  

I’m already testing that feature. Feel free to try it out in the latest release!  
 [[BlenderManager v0.0.8](https://github.com/verlorengest/BlenderManager/releases/tag/v0.0.8)](https://github.com/verlorengest/BlenderManager/releases/tag/v0.0.8)
