### ISSUE TITLE
1.0 版本错误提示和功能建议

### ISSUE THREAD

**Issue by BopSun** [verlorengest/BlenderManager#6]
Hi，我下载了1.0版本，每次启动约3分钟后弹出错误提示如下：
![image](https://github.com/user-attachments/assets/a7a66373-baaf-4e5d-9c09-01a029daa9f0)

另外当我的主运行版本是4.2的时候，如果点击了 Check Updates 后会自动下载并安装 4.3 版本。我认为它应该检查 4.2 的最新版本而不是用 4.3 来覆盖我的默认启动版本。并且，我无法在 Version Management 中看到我刚刚跟新的 4.3 版本。Main Menu 中也不会刷新更新的版本显示，只有重新打开软件才会更新这些内容。

现在我能够在 Project Management 中看到每个文件所使用的Blender版本，并且通过右键选择对应的 Blender 版本打开它，但这些操作只能在这里使用。如果我能够在 Main Menu 也能这么做就更好了。最终我希望能够通过双击自动激活正确的 Blender 版本打开文件。
当我尝试在 Project Management 中添加新项目文件夹时 BlenderManager 停止响应，它似乎将我新指定的文件夹内所有文件都复制到了 Browse 文件夹内，而如果我直接在 Browse 文件夹内新建文件夹，因为里面没有包含 Blender 文件，所以我无法从下面的列表中看到这个文件夹。而 Main Menu 中的 Create Project 只是激活了 Blender ，而不会真的创建一个 Blender 文件，所以我可以把新建的文件保存到任何一个位置。 我觉得这两个按钮的逻辑并不相同，也不符合你对他们的定义。

Version Management 记不住我的操作系统选项，但是我认为这个设置应该放在软件设置内，而不是在这个界面中显示，因为我不可能使用中替换我的操作系统。我觉得目前这个安装界面过于繁琐了。而真正需要的信息可以用一个简单的列表表示：
已安装的版本 | 下载最新版本 | 最近打开的文件
Blender 3.6.9 | Blender 3.6.18 | xx-xx.blender
Blender 3.6.12 | Blender 3.6.18 | xxxx-xx.blender
Blender 4.2.3 | Bneder 4.2.4 | xxxxx-xx.blender
「安装其它版本」「删除已安装版本」

Bop

**Comment by verlorengest** [comment]
Hey There, 

Regarding the update issue, I can add an optional checkbox in the settings menu to restrict updates to the current major version (e.g., updating 4.2.2 to 4.2.3 but not beyond). This will allow users to control their update preferences more effectively.

The freezing issue when adding new projects typically occurs with large numbers of files. As for folders without .blend files, they are intentionally excluded from the list to focus on relevant directories. Including such folders might not be meaningful in this context.

The Create Project button is designed for quick project creation. If you don’t save the file, no project file will be created. Let me know if there's a specific issue or workflow you'd like improved here.

As for Version Management, I’ve implemented a function to automatically find operating system and choose it, which will be included in the next patch. I also plan to enhance this section over time for better usability.

Thank you for your valuable feedback!

**Comment by BopSun** [comment]
对于Create Project，目前的方式会因为手动保存 Blender 文件到错误的文件夹而无法进行管理。所以我觉得最佳方式是自动生成一个 Blender 文件，然后再用对应的 Blender 版本打开它。

对于项目管理，一般来说会包括整个过程中产生的各种类型文件。而针对这个工具，我觉得把它定位成任务管理可能会更好。因为 Blender 可以包括各种不同类型的任务，比如建模任务，贴图任务等，所以可能需要一个简单的任务管理列表，有点像目前的 Main Menu 列表，但还应该包括一些与任务相关的的功能，比如任务目标（如模型，贴图），完成进度等。这些可以是字段或包含时间节点的完成标记等。

这些都是我的期望，但仅任务管理一项，就有很大的可拓展空间，具体如何发展，完全取决于你的决定。

Bop
